### ISSUE TITLE
Issues の Labels を整理する

### ISSUE THREAD

**Issue by nikukyugamer** [nikukyugamer/challenging-rails#2]
**Is your feature request related to a problem? Please describe.**
- このアプリ開発に適した Issue のカテゴリ分けをしたい
- 可能ならラベルのテンプレートを使いまわしたい
  - GitLab ならできたはずだが……

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by corselia** [comment]
ツールでやりたいので、探す。
